import { StyleSheet } from 'react-native';
import { normalize } from '../../utils/scaling';

export const styles = StyleSheet.create({
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: normalize(28),
        marginBottom: normalize(14),
        paddingHorizontal: normalize(4),
    },
    sectionTitle: {
        fontSize: normalize(20),
        fontWeight: '700',
        color: '#222',
        letterSpacing: 0.2,
    },
    seeAllText: {
        color: '#6C6FD1',
        fontSize: normalize(15),
        fontWeight: '600',
        letterSpacing: 0.1,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)'
    },
    modalContent: {
        backgroundColor: '#fff',
        padding: normalize(24),
        borderRadius: normalize(12),
        width: normalize(300)
    },
    modalTitle: {
        fontWeight: 'bold',
        fontSize: normalize(18),
        marginBottom: normalize(16)
    },
    cityButton: {
        padding: normalize(12),
        borderRadius: normalize(8),
        marginVertical: normalize(4)
    },
    cityText: {
        fontSize: normalize(16)
    },
    currentLocationButton: {
        marginTop: normalize(16),
        padding: normalize(12),
        borderRadius: normalize(8)
    },
    currentLocationText: {
        color: '#6C6FD1',
        textAlign: 'center',
        fontSize: normalize(14)
    },
    container: {
        flex: 1,
        padding: normalize(18),
        backgroundColor: '#f5f7fa',
    },
    titleContainer: {
        marginTop: normalize(16),
        marginBottom: normalize(14),
    },
    title: {
        fontSize: normalize(21),
        fontWeight: 'bold',
        color: '#222',
        marginBottom: normalize(4),
    },
    subtitle: {
        fontSize: normalize(16),
        color: '#666',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: normalize(12),
        padding: normalize(12),
        backgroundColor: '#fff',
        borderRadius: normalize(18),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 8,
        elevation: 2,
    },
    smallText: {
        fontSize: normalize(13),
        color: '#8a8a8a',
        fontWeight: '500',
    },
    locationText: {
        fontSize: normalize(17),
        fontWeight: '700',
        marginLeft: normalize(4),
        color: '#222',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    notificationBtn: {
        backgroundColor: '#f5f7fa',
        padding: normalize(10),
        borderRadius: normalize(16),
        marginLeft: normalize(8),
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 1,
    },
    badge: {
        position: 'absolute',
        top: -6,
        right: -6,
        backgroundColor: '#FF3B30',
        borderRadius: 12,
        minWidth: 22,
        height: 22,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 5,
        borderWidth: 2,
        borderColor: '#fff',
    },
    badgeText: {
        color: 'white',
        fontSize: 12,
        fontWeight: 'bold',
    },
    button: {
        backgroundColor: '#8d8ff3',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: normalize(16),
        borderRadius: normalize(24),
        marginVertical: normalize(18),
        shadowColor: '#8d8ff3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.18,
        shadowRadius: 8,
        elevation: 4,
    },
    buttonText: {
        color: '#fff',
        fontSize: normalize(17),
        fontWeight: 'bold',
        marginLeft: normalize(10),
        letterSpacing: 0.2,
    },
    tabs: {
        flexDirection: 'row',
        marginTop: normalize(24),
        marginBottom: normalize(14),
        backgroundColor: '#6C6FD1',
        borderRadius: normalize(28),
        padding: normalize(6),
        borderWidth: 1,
        borderColor: 'rgba(141,143,243,0.10)',
        shadowColor: '#6C6FD1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
        backdropFilter: 'blur(8px)', // for web, ignored on native
    },
    tab: {
        flex: 1,
        paddingVertical: normalize(16),
        backgroundColor: 'rgba(245,247,250,0.85)',
        marginHorizontal: normalize(4),
        borderRadius: normalize(22),
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'background-color 0.2s, transform 0.2s, opacity 0.2s',
        shadowColor: 'transparent',
        borderWidth: 1,
        borderColor: 'rgba(79,120,241,0.06)',
        opacity: 0.92,
    },
    activeTab: {
        backgroundColor: 'linear-gradient(90deg, #6C6FD1 0%, #6fa8ff 100%)', // for web, fallback below
        backgroundColor: '#6C6FD1', // fallback for native
        shadowColor: '#6C6FD1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1.5,
        borderColor: '#6C6FD1',
        transform: [{ scale: 1.04 }],
        opacity: 1,
    },
    tabText: {
        color: '#6C6FD1',
        fontSize: normalize(16),
        fontWeight: '700',
        letterSpacing: 0.2,
        fontFamily: 'System',
        textAlign: 'center',
    },
    tabTextActive: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: normalize(16),
        letterSpacing: 0.2,
        fontFamily: 'System',
        textAlign: 'center',
        textShadowColor: 'rgba(0,0,0,0.08)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
});